
package com.ihsinformatics.tbr3smssurvey.model;

// Generated Jul 21, 2014 9:51:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -6724434644427720743L;
	private QuestionId	id;
	private String		questionText;
	private String		answerPattern;
	private String		uuid;

	public Question ()
	{
	}

	public Question (QuestionId id)
	{
		this.id = id;
	}

	public Question (QuestionId id, String questionText, String answerPattern, String uuid)
	{
		this.id = id;
		this.questionText = questionText;
		this.answerPattern = answerPattern;
		this.uuid = uuid;
	}

	public QuestionId getId ()
	{
		return this.id;
	}

	public void setId (QuestionId id)
	{
		this.id = id;
	}

	public String getQuestionText ()
	{
		return this.questionText;
	}

	public void setQuestionText (String questionText)
	{
		this.questionText = questionText;
	}

	public String getAnswerPattern ()
	{
		return this.answerPattern;
	}

	public void setAnswerPattern (String answerPattern)
	{
		this.answerPattern = answerPattern;
	}

	public String getUuid ()
	{
		return this.uuid;
	}

	public void setUuid (String uuid)
	{
		this.uuid = uuid;
	}

}
