
package com.ihsinformatics.tbr3smssurvey.model;

// Generated Jul 21, 2014 9:51:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * QuestionId generated by hbm2java
 */
public class QuestionId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2331155667642967172L;
	private int	surveyId;
	private int	questionId;

	public QuestionId ()
	{
	}

	public QuestionId (int surveyId, int questionId)
	{
		this.surveyId = surveyId;
		this.questionId = questionId;
	}

	public int getSurveyId ()
	{
		return this.surveyId;
	}

	public void setSurveyId (int surveyId)
	{
		this.surveyId = surveyId;
	}

	public int getQuestionId ()
	{
		return this.questionId;
	}

	public void setQuestionId (int questionId)
	{
		this.questionId = questionId;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionId))
			return false;
		QuestionId castOther = (QuestionId) other;

		return (this.getSurveyId () == castOther.getSurveyId ()) && (this.getQuestionId () == castOther.getQuestionId ());
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + this.getSurveyId ();
		result = 37 * result + this.getQuestionId ();
		return result;
	}

}
